### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by jaredsburrows**
@hidroh 
I was going to update Robolectric to `3.1.1` but that failed many tests and required a lot more changes.

### CODE REVIEW

**Comment by hidroh** [comment]
I did try some time ago when 3.1 was still in RC, but there have been a lot of changes that would break so I think I'll stick with 3.0 for a while. As for OkHttp 3.4, there are changes to clear text traffic check that may break tests.

**Comment by jaredsburrows** [comment]
All tests run fine, I just forgot to update the `.travis.yml` file.

**Comment by hidroh** [comment]
Thanks, one small request, can you also update README.md to specify latest build tools & support library versions as well?

**Comment by jaredsburrows** [comment]
@hidroh Done.

**Pull request merged**
